import "./globals.css";

export const metadata = {
  title: "José Mª Martín",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-zinc-950 leading-relaxed text-zinc-400 antialiased selection:bg-zinc-300 selection:text-zinc-900">{children}</body>
    </html>
  );
}